### ISSUE TITLE
Add eMQTT5 in Client libraries list

### ISSUE THREAD

**Issue by InfoLibre** [mqtt/mqtt.org#160]
In https://mqtt.org/software/, eMqtt5 is missing in the MATT client libraries list.

https://github.com/X-Ryl669/eMQTT5

**Comment by B-Weiss** [comment]
Feel free to create a PR and add it to the list

**Comment by InfoLibre** [comment]
:question: :question: :question: :question: :question: :question: :question: :question: :question: :question: :question: :question: :question: :question: :question: :question:

**Comment by InfoLibre** [comment]
What is a PR?

**Comment by B-Weiss** [comment]
PR = Pull Request. Add your software to the client library and create a pull request.

**Comment by InfoLibre** [comment]
Done.
