### ISSUE TITLE
Server Support Documentation - Mosquitto / MQTT.js

### ISSUE THREAD

**Issue by Andreyooo** [mqtt/mqtt.org#70]
Hi, thx for the great summary of brokers in the server support documentation. I'm actively using Mosquitto and MQTT.js so I'd like to suggest to update some information. 
1) Mosquitto is supporting MQTT 5.0 as stated on their homepage, which is not yet stated in the documentation.
2) MQTT.js is a javascript mqtt-client library, so I don't believe it belongs into the list.

**Comment by iskerrett** [comment]
Can I suggest you submit a pull request for the changes you want to make to the Mosquitto listing. 

I don't really understand your point about MQTT.js. It is not on the list of servers.

**Comment by Andreyooo** [comment]
Sry I'm not familiar with PR's. I'm reffering to this page https://github.com/mqtt/mqtt.github.io/wiki/server-support, where MQTT.js is listed as a broker and mosquitto is said to not support MQTT 5.0.
